apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rest-service-deployment
  namespace: rest-apis
spec:
  maxReplicas: 4
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rest-service-deployment
